# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('membership', models.CharField(max_length=100)),
                ('register_date', models.CharField(max_length=100)),
            ],
        ),
    ]
