# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('group_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('membership', models.CharField(max_length=100)),
                ('register_date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('date_of_attack', models.CharField(max_length=100)),
                ('date_of_compromise', models.CharField(default='', max_length=100)),
                ('duration', models.CharField(default='', max_length=100)),
                ('vulnerable', models.CharField(default='Still Safe', max_length=2)),
                ('auto_id', models.IntegerField(default=0)),
                ('group_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='services.groups')),
            ],
        ),
        migrations.CreateModel(
            name='victims',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='', max_length=100)),
                ('useremail', models.CharField(max_length=100)),
                ('date_of_attack', models.CharField(max_length=100)),
                ('date_of_compromise', models.CharField(default='', max_length=100)),
                ('duration', models.CharField(default='', max_length=100)),
                ('vulnerable', models.CharField(default='Still Safe', max_length=100)),
                ('url', models.CharField(default='', max_length=300)),
                ('auto_id', models.CharField(default='', max_length=300)),
                ('predator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.members')),
            ],
        ),
    ]
