# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='victims',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useremail', models.CharField(max_length=100)),
                ('vulnerable', models.CharField(max_length=2)),
                ('date_of_attack', models.CharField(max_length=100)),
            ],
        ),
    ]
