# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_victims'),
    ]

    operations = [
        migrations.AddField(
            model_name='victims',
            name='fullname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
