# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_victims_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='victims',
            name='auto_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='victims',
            name='vulnerable',
            field=models.CharField(default='Still Safe', max_length=2),
        ),
    ]
