# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-19 03:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20170719_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='date_created',
            field=models.CharField(default=datetime.datetime(2017, 7, 19, 5, 11, 24, 862140), max_length=100),
        ),
        migrations.AlterField(
            model_name='members',
            name='register_date',
            field=models.CharField(default=datetime.datetime(2017, 7, 19, 5, 11, 24, 661842), max_length=100),
        ),
    ]
