# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20170412_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('group_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('membership', models.CharField(max_length=100)),
                ('register_date', models.CharField(max_length=100)),
                ('group_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='services.groups')),
            ],
        ),
        migrations.AddField(
            model_name='victims',
            name='date_of_compromise',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='victims',
            name='duration',
            field=models.CharField(default='', max_length=100),
        ),
    ]
