# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20170418_0913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='membership',
            new_name='date_of_attack',
        ),
        migrations.RemoveField(
            model_name='users',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='users',
            name='password',
        ),
        migrations.RemoveField(
            model_name='users',
            name='register_date',
        ),
        migrations.AddField(
            model_name='users',
            name='auto_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='date_of_compromise',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='duration',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='vulnerable',
            field=models.CharField(default='Still Safe', max_length=2),
        ),
    ]
