# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20170418_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='victims',
            name='url',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='victims',
            name='vulnerable',
            field=models.CharField(default='Still Safe', max_length=100),
        ),
    ]
