# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 08:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20170721_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='landin_page',
            fields=[
                ('page_id', models.AutoField(primary_key=True, serialize=False)),
                ('page_name', models.CharField(default='', max_length=100)),
                ('page_content', models.CharField(default='', max_length=1000000000000)),
            ],
        ),
        migrations.AlterField(
            model_name='campaign',
            name='date_created',
            field=models.CharField(default=datetime.datetime(2017, 7, 21, 10, 45, 42, 583867), max_length=100),
        ),
        migrations.AlterField(
            model_name='members',
            name='register_date',
            field=models.CharField(default=datetime.datetime(2017, 7, 21, 10, 45, 42, 553867), max_length=100),
        ),
        migrations.AddField(
            model_name='landin_page',
            name='member_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='services.members'),
        ),
    ]
