# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-19 06:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20170421_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='campaign',
            fields=[
                ('campaign_id', models.AutoField(primary_key=True, serialize=False)),
                ('campaign_name', models.CharField(default='', max_length=100)),
                ('campaign_desc', models.CharField(default='', max_length=300)),
                ('date_created', models.CharField(default=datetime.datetime(2017, 10, 19, 8, 43, 23, 369503), max_length=100)),
                ('started', models.IntegerField(default=0)),
                ('stoped', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='campaign_clicks',
            fields=[
                ('click_id', models.AutoField(primary_key=True, serialize=False)),
                ('long_url', models.CharField(default='', max_length=300)),
                ('short_url', models.CharField(default='', max_length=300)),
                ('ip_add', models.CharField(default='', max_length=30)),
                ('date_of_compromise', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='landin_page',
            fields=[
                ('page_id', models.AutoField(primary_key=True, serialize=False)),
                ('page_name', models.CharField(default='', max_length=100)),
                ('page_content', models.CharField(default='', max_length=1000000000000)),
                ('page_upload', models.FileField(default='No Image File', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='quick_attack',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(default='', max_length=100)),
                ('useremail', models.CharField(max_length=100)),
                ('sent_date', models.CharField(default='', max_length=100)),
                ('url_id', models.CharField(default='', max_length=16)),
                ('long_url', models.CharField(default='', max_length=100)),
                ('short_url', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='Safe', max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='quick_attack_clicks',
            fields=[
                ('click_id', models.AutoField(primary_key=True, serialize=False)),
                ('long_url', models.CharField(default='', max_length=300)),
                ('short_url', models.CharField(default='', max_length=300)),
                ('ip_add', models.CharField(default='', max_length=30)),
                ('date_of_compromise', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='sending_profiles',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('profile_name', models.CharField(default='', max_length=100)),
                ('profile_email', models.CharField(default='', max_length=100)),
                ('profile_password', models.CharField(default='', max_length=100)),
                ('profile_server', models.CharField(default='', max_length=100)),
                ('profile_port', models.IntegerField(default=0, max_length=10)),
                ('profile_header', models.CharField(default='', max_length=100)),
                ('created_date', models.CharField(default=datetime.datetime(2017, 10, 19, 8, 43, 23, 372503), max_length=100)),
                ('campaign_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='services.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='user_groups',
            fields=[
                ('user_group_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='userss',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(default='', max_length=100)),
                ('useremail', models.CharField(max_length=100)),
                ('sent_date', models.CharField(default=datetime.datetime(2017, 10, 19, 8, 43, 23, 370503), max_length=100)),
                ('url_id', models.CharField(default='', max_length=16)),
                ('long_url', models.CharField(default='', max_length=100)),
                ('short_url', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='Safe', max_length=11)),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='group_id',
        ),
        migrations.DeleteModel(
            name='victims',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='id',
        ),
        migrations.RemoveField(
            model_name='members',
            name='membership',
        ),
        migrations.AddField(
            model_name='groups',
            name='created_date',
            field=models.CharField(default=datetime.datetime(2017, 10, 19, 8, 43, 23, 370003), max_length=100),
        ),
        migrations.AddField(
            model_name='groups',
            name='group_id',
            field=models.AutoField(default='', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='groups',
            name='member_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='services.members'),
        ),
        migrations.AddField(
            model_name='members',
            name='confirm_id',
            field=models.CharField(default='0', max_length=16),
        ),
        migrations.AddField(
            model_name='members',
            name='confirmed',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='groups',
            name='group_description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='groups',
            name='group_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='members',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='members',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='members',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='members',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='members',
            name='organization',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='members',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='members',
            name='register_date',
            field=models.CharField(default=datetime.datetime(2017, 10, 19, 8, 43, 23, 354503), max_length=100),
        ),
        migrations.AlterField(
            model_name='members',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='users',
        ),
        migrations.AddField(
            model_name='userss',
            name='group_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='services.groups'),
        ),
        migrations.AddField(
            model_name='userss',
            name='member_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='services.members'),
        ),
        migrations.AddField(
            model_name='user_groups',
            name='group_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='services.groups'),
        ),
        migrations.AddField(
            model_name='user_groups',
            name='member_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='services.members'),
        ),
        migrations.AddField(
            model_name='user_groups',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='services.quick_attack'),
        ),
        migrations.AddField(
            model_name='sending_profiles',
            name='member_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='services.members'),
        ),
        migrations.AddField(
            model_name='quick_attack_clicks',
            name='member_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='services.members'),
        ),
        migrations.AddField(
            model_name='quick_attack_clicks',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='services.quick_attack'),
        ),
        migrations.AddField(
            model_name='quick_attack',
            name='group_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='services.groups'),
        ),
        migrations.AddField(
            model_name='quick_attack',
            name='member_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='services.members'),
        ),
        migrations.AddField(
            model_name='landin_page',
            name='member_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='services.members'),
        ),
        migrations.AddField(
            model_name='campaign_clicks',
            name='member_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='services.members'),
        ),
        migrations.AddField(
            model_name='campaign_clicks',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='services.userss'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='member_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='services.members'),
        ),
        migrations.AddField(
            model_name='groups',
            name='campaign_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='services.campaign'),
        ),
    ]
