# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 10:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20170721_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_desc',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='date_created',
            field=models.CharField(default=datetime.datetime(2017, 7, 21, 12, 19, 48, 912867), max_length=100),
        ),
        migrations.AlterField(
            model_name='members',
            name='register_date',
            field=models.CharField(default=datetime.datetime(2017, 7, 21, 12, 19, 48, 892867), max_length=100),
        ),
    ]
