# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-19 06:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20171019_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='date_created',
            field=models.CharField(default=datetime.datetime(2017, 10, 19, 8, 45, 21, 505503), max_length=100),
        ),
        migrations.AlterField(
            model_name='groups',
            name='created_date',
            field=models.CharField(default=datetime.datetime(2017, 10, 19, 8, 45, 21, 506003), max_length=100),
        ),
        migrations.AlterField(
            model_name='members',
            name='register_date',
            field=models.CharField(default=datetime.datetime(2017, 10, 19, 8, 45, 21, 491003), max_length=100),
        ),
        migrations.AlterField(
            model_name='sending_profiles',
            name='created_date',
            field=models.CharField(default=datetime.datetime(2017, 10, 19, 8, 45, 21, 508003), max_length=100),
        ),
        migrations.AlterField(
            model_name='userss',
            name='sent_date',
            field=models.CharField(default=datetime.datetime(2017, 10, 19, 8, 45, 21, 506503), max_length=100),
        ),
    ]
