# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-16 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='campaigns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.CharField(max_length=100)),
                ('campaign_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='quick_attack',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(default='', max_length=100)),
                ('useremail', models.CharField(max_length=100)),
                ('date_of_attack', models.CharField(max_length=100)),
                ('date_of_compromise', models.CharField(default='', max_length=100)),
                ('duration', models.CharField(default='', max_length=100)),
                ('vulnerable', models.CharField(default='Still Safe', max_length=100)),
                ('long_url', models.CharField(default='', max_length=300)),
                ('short_url', models.CharField(default='', max_length=300)),
                ('auto_id', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='quick_attack_clicks',
            fields=[
                ('click_id', models.AutoField(primary_key=True, serialize=False)),
                ('long_url', models.CharField(default='', max_length=300)),
                ('short_url', models.CharField(default='', max_length=300)),
                ('date_of_compromise', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='members',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='quick_attack_clicks',
            name='predator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.members'),
        ),
        migrations.AddField(
            model_name='quick_attack_clicks',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.quick_attack'),
        ),
        migrations.AddField(
            model_name='quick_attack',
            name='predator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.members'),
        ),
    ]
