# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-19 02:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20170716_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='campaign',
            fields=[
                ('campaign_id', models.AutoField(primary_key=True, serialize=False)),
                ('campaign_name', models.CharField(default='', max_length=100)),
                ('date_created', models.CharField(default=datetime.datetime(2017, 7, 19, 4, 29, 24, 290591), max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='groups',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(default='', max_length=100)),
                ('campaign_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='services.campaign')),
            ],
        ),
        migrations.DeleteModel(
            name='campaigns',
        ),
        migrations.RenameField(
            model_name='quick_attack',
            old_name='date_of_compromise',
            new_name='sent_date',
        ),
        migrations.RemoveField(
            model_name='members',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='quick_attack',
            name='auto_id',
        ),
        migrations.RemoveField(
            model_name='quick_attack',
            name='date_of_attack',
        ),
        migrations.RemoveField(
            model_name='quick_attack',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='quick_attack',
            name='predator',
        ),
        migrations.RemoveField(
            model_name='quick_attack',
            name='vulnerable',
        ),
        migrations.RemoveField(
            model_name='quick_attack_clicks',
            name='predator',
        ),
        migrations.AddField(
            model_name='members',
            name='confirm_id',
            field=models.CharField(default='0', max_length=16),
        ),
        migrations.AddField(
            model_name='members',
            name='confirmed',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='quick_attack',
            name='member_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='services.members'),
        ),
        migrations.AddField(
            model_name='quick_attack',
            name='status',
            field=models.CharField(default='Safe', max_length=11),
        ),
        migrations.AddField(
            model_name='quick_attack',
            name='url_id',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='quick_attack_clicks',
            name='member_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='services.members'),
        ),
        migrations.AlterField(
            model_name='members',
            name='register_date',
            field=models.CharField(default=datetime.datetime(2017, 7, 19, 4, 29, 24, 127018), max_length=100),
        ),
        migrations.AlterField(
            model_name='quick_attack',
            name='long_url',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='quick_attack',
            name='short_url',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='quick_attack_clicks',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='services.quick_attack'),
        ),
        migrations.AddField(
            model_name='groups',
            name='member_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='services.members'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='member_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='services.members'),
        ),
        migrations.AddField(
            model_name='quick_attack',
            name='group_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='services.groups'),
        ),
    ]
