# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-19 04:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20170719_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='quick_attack_clicks',
            name='ip_add',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='date_created',
            field=models.CharField(default=datetime.datetime(2017, 7, 19, 6, 49, 42, 348984), max_length=100),
        ),
        migrations.AlterField(
            model_name='members',
            name='register_date',
            field=models.CharField(default=datetime.datetime(2017, 7, 19, 6, 49, 42, 331484), max_length=100),
        ),
    ]
