# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 13:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20170719_0649'),
    ]

    operations = [
        migrations.CreateModel(
            name='userss',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(default='', max_length=100)),
                ('useremail', models.CharField(max_length=100)),
                ('sent_date', models.CharField(default='', max_length=100)),
                ('url_id', models.CharField(default='', max_length=16)),
                ('long_url', models.CharField(default='', max_length=100)),
                ('short_url', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='Safe', max_length=11)),
                ('group_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='services.groups')),
            ],
        ),
        migrations.AlterField(
            model_name='campaign',
            name='date_created',
            field=models.CharField(default=datetime.datetime(2017, 7, 20, 15, 45, 59, 912867), max_length=100),
        ),
        migrations.AlterField(
            model_name='members',
            name='register_date',
            field=models.CharField(default=datetime.datetime(2017, 7, 20, 15, 45, 59, 892867), max_length=100),
        ),
        migrations.AddField(
            model_name='userss',
            name='member_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='services.members'),
        ),
    ]
