# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 07:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20170720_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='date_created',
            field=models.CharField(default=datetime.datetime(2017, 7, 21, 9, 20, 7, 596867), max_length=100),
        ),
        migrations.AlterField(
            model_name='members',
            name='register_date',
            field=models.CharField(default=datetime.datetime(2017, 7, 21, 9, 20, 7, 582867), max_length=100),
        ),
    ]
