# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 11:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_auto_20170802_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='group_description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='date_created',
            field=models.CharField(default=datetime.datetime(2017, 8, 2, 13, 36, 41, 707000), max_length=100),
        ),
        migrations.AlterField(
            model_name='groups',
            name='created_date',
            field=models.CharField(default=datetime.datetime(2017, 8, 2, 13, 36, 41, 707000), max_length=100),
        ),
        migrations.AlterField(
            model_name='members',
            name='register_date',
            field=models.CharField(default=datetime.datetime(2017, 8, 2, 13, 36, 41, 692000), max_length=100),
        ),
    ]
