# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 13:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_auto_20170802_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='attack_users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('useremail', models.CharField(max_length=100)),
                ('sent_date', models.CharField(default='', max_length=100)),
                ('url_id', models.CharField(default='', max_length=16)),
                ('long_url', models.CharField(default='', max_length=100)),
                ('short_url', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='Safe', max_length=11)),
            ],
        ),
        migrations.AlterField(
            model_name='campaign',
            name='date_created',
            field=models.CharField(default=datetime.datetime(2017, 8, 2, 15, 14, 17, 550000), max_length=100),
        ),
        migrations.AlterField(
            model_name='groups',
            name='created_date',
            field=models.CharField(default=datetime.datetime(2017, 8, 2, 15, 14, 17, 551000), max_length=100),
        ),
        migrations.AlterField(
            model_name='members',
            name='register_date',
            field=models.CharField(default=datetime.datetime(2017, 8, 2, 15, 14, 17, 535000), max_length=100),
        ),
        migrations.AddField(
            model_name='attack_users',
            name='group_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='services.groups'),
        ),
        migrations.AddField(
            model_name='attack_users',
            name='member_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='services.members'),
        ),
    ]
