# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 06:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_auto_20170802_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='sending_profiles',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('profile_name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='campaign',
            name='date_created',
            field=models.CharField(default=datetime.datetime(2017, 8, 3, 8, 56, 31, 228000), max_length=100),
        ),
        migrations.AlterField(
            model_name='groups',
            name='created_date',
            field=models.CharField(default=datetime.datetime(2017, 8, 3, 8, 56, 31, 228000), max_length=100),
        ),
        migrations.AlterField(
            model_name='members',
            name='register_date',
            field=models.CharField(default=datetime.datetime(2017, 8, 3, 8, 56, 31, 212000), max_length=100),
        ),
        migrations.AddField(
            model_name='sending_profiles',
            name='campaign_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='services.campaign'),
        ),
        migrations.AddField(
            model_name='sending_profiles',
            name='member_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='services.members'),
        ),
    ]
