# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 09:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_auto_20170803_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attack_users',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='attack_users',
            name='member_id',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='date_created',
            field=models.CharField(default=datetime.datetime(2017, 8, 3, 11, 0, 57, 594000), max_length=100),
        ),
        migrations.AlterField(
            model_name='groups',
            name='created_date',
            field=models.CharField(default=datetime.datetime(2017, 8, 3, 11, 0, 57, 594000), max_length=100),
        ),
        migrations.AlterField(
            model_name='members',
            name='register_date',
            field=models.CharField(default=datetime.datetime(2017, 8, 3, 11, 0, 57, 569000), max_length=100),
        ),
        migrations.DeleteModel(
            name='attack_users',
        ),
    ]
