# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 08:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_auto_20170803_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='sending_profiles',
            name='profile_header',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sending_profiles',
            name='profile_password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sending_profiles',
            name='profile_port',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='sending_profiles',
            name='profile_server',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='date_created',
            field=models.CharField(default=datetime.datetime(2017, 8, 7, 10, 41, 40, 580000), max_length=100),
        ),
        migrations.AlterField(
            model_name='groups',
            name='created_date',
            field=models.CharField(default=datetime.datetime(2017, 8, 7, 10, 41, 40, 580000), max_length=100),
        ),
        migrations.AlterField(
            model_name='members',
            name='register_date',
            field=models.CharField(default=datetime.datetime(2017, 8, 7, 10, 41, 40, 564000), max_length=100),
        ),
        migrations.AlterField(
            model_name='userss',
            name='sent_date',
            field=models.CharField(default=datetime.datetime(2017, 8, 7, 10, 41, 40, 581000), max_length=100),
        ),
    ]
