# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 10:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_auto_20170807_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='sending_profiles',
            name='profile_email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='date_created',
            field=models.CharField(default=datetime.datetime(2017, 8, 7, 12, 12, 51, 731000), max_length=100),
        ),
        migrations.AlterField(
            model_name='groups',
            name='created_date',
            field=models.CharField(default=datetime.datetime(2017, 8, 7, 12, 12, 51, 731000), max_length=100),
        ),
        migrations.AlterField(
            model_name='members',
            name='register_date',
            field=models.CharField(default=datetime.datetime(2017, 8, 7, 12, 12, 51, 716000), max_length=100),
        ),
        migrations.AlterField(
            model_name='userss',
            name='sent_date',
            field=models.CharField(default=datetime.datetime(2017, 8, 7, 12, 12, 51, 732000), max_length=100),
        ),
    ]
