# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-10 09:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_auto_20170807_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='landin_page',
            name='page_upload',
            field=models.FileField(default='No Image File', upload_to=''),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='date_created',
            field=models.CharField(default=datetime.datetime(2017, 10, 10, 11, 44, 36, 547000), max_length=100),
        ),
        migrations.AlterField(
            model_name='groups',
            name='created_date',
            field=models.CharField(default=datetime.datetime(2017, 10, 10, 11, 44, 36, 547000), max_length=100),
        ),
        migrations.AlterField(
            model_name='members',
            name='register_date',
            field=models.CharField(default=datetime.datetime(2017, 10, 10, 11, 44, 36, 533000), max_length=100),
        ),
        migrations.AlterField(
            model_name='sending_profiles',
            name='created_date',
            field=models.CharField(default=datetime.datetime(2017, 10, 10, 11, 44, 36, 550000), max_length=100),
        ),
        migrations.AlterField(
            model_name='userss',
            name='sent_date',
            field=models.CharField(default=datetime.datetime(2017, 10, 10, 11, 44, 36, 548000), max_length=100),
        ),
    ]
