# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-17 05:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_auto_20171010_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='campaign_clicks',
            fields=[
                ('click_id', models.AutoField(primary_key=True, serialize=False)),
                ('long_url', models.CharField(default='', max_length=300)),
                ('short_url', models.CharField(default='', max_length=300)),
                ('ip_add', models.CharField(default='', max_length=30)),
                ('date_of_compromise', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='campaign',
            name='date_created',
            field=models.CharField(default=datetime.datetime(2017, 10, 17, 7, 40, 58, 683003), max_length=100),
        ),
        migrations.AlterField(
            model_name='groups',
            name='created_date',
            field=models.CharField(default=datetime.datetime(2017, 10, 17, 7, 40, 58, 683003), max_length=100),
        ),
        migrations.AlterField(
            model_name='members',
            name='register_date',
            field=models.CharField(default=datetime.datetime(2017, 10, 17, 7, 40, 58, 667003), max_length=100),
        ),
        migrations.AlterField(
            model_name='sending_profiles',
            name='created_date',
            field=models.CharField(default=datetime.datetime(2017, 10, 17, 7, 40, 58, 685503), max_length=100),
        ),
        migrations.AlterField(
            model_name='userss',
            name='sent_date',
            field=models.CharField(default=datetime.datetime(2017, 10, 17, 7, 40, 58, 683503), max_length=100),
        ),
        migrations.AddField(
            model_name='campaign_clicks',
            name='member_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='services.members'),
        ),
        migrations.AddField(
            model_name='campaign_clicks',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='services.userss'),
        ),
    ]
