# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-20 05:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_auto_20171017_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='landing_page_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='services.landin_page'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='sending_profile_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='services.sending_profiles'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='date_created',
            field=models.CharField(default=datetime.datetime(2017, 10, 20, 7, 51, 42, 557503), max_length=100),
        ),
        migrations.AlterField(
            model_name='groups',
            name='created_date',
            field=models.CharField(default=datetime.datetime(2017, 10, 20, 7, 51, 42, 558003), max_length=100),
        ),
        migrations.AlterField(
            model_name='members',
            name='register_date',
            field=models.CharField(default=datetime.datetime(2017, 10, 20, 7, 51, 42, 542003), max_length=100),
        ),
        migrations.AlterField(
            model_name='sending_profiles',
            name='created_date',
            field=models.CharField(default=datetime.datetime(2017, 10, 20, 7, 51, 42, 560503), max_length=100),
        ),
        migrations.AlterField(
            model_name='sending_profiles',
            name='profile_port',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userss',
            name='sent_date',
            field=models.CharField(default=datetime.datetime(2017, 10, 20, 7, 51, 42, 558503), max_length=100),
        ),
    ]
