# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-12 10:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0023_auto_20171023_0830'),
    ]

    operations = [
        migrations.CreateModel(
            name='email_template',
            fields=[
                ('template_id', models.AutoField(primary_key=True, serialize=False)),
                ('template_name', models.CharField(default='', max_length=100)),
                ('message', models.CharField(default='', max_length=1000000000000)),
                ('template_upload', models.FileField(default='No File Uploaded', upload_to='')),
                ('created_date', models.CharField(default=datetime.datetime(2017, 11, 12, 12, 49, 56, 47000), max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='campaign',
            name='date_created',
            field=models.CharField(default=datetime.datetime(2017, 11, 12, 12, 49, 56, 42000), max_length=100),
        ),
        migrations.AlterField(
            model_name='groups',
            name='created_date',
            field=models.CharField(default=datetime.datetime(2017, 11, 12, 12, 49, 56, 43000), max_length=100),
        ),
        migrations.AlterField(
            model_name='members',
            name='register_date',
            field=models.CharField(default=datetime.datetime(2017, 11, 12, 12, 49, 56, 17000), max_length=100),
        ),
        migrations.AlterField(
            model_name='sending_profiles',
            name='created_date',
            field=models.CharField(default=datetime.datetime(2017, 11, 12, 12, 49, 56, 46500), max_length=100),
        ),
        migrations.AlterField(
            model_name='userss',
            name='sent_date',
            field=models.CharField(default=datetime.datetime(2017, 11, 12, 12, 49, 56, 43500), max_length=100),
        ),
        migrations.AddField(
            model_name='email_template',
            name='member_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='services.members'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='template_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='services.email_template'),
        ),
    ]
