# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 07:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0024_auto_20171112_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='phish_data',
            fields=[
                ('user_group_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='campaign',
            name='date_created',
            field=models.CharField(default=datetime.datetime(2017, 11, 15, 9, 25, 37, 615000), max_length=100),
        ),
        migrations.AlterField(
            model_name='email_template',
            name='created_date',
            field=models.CharField(default=datetime.datetime(2017, 11, 15, 9, 25, 37, 618500), max_length=100),
        ),
        migrations.AlterField(
            model_name='groups',
            name='created_date',
            field=models.CharField(default=datetime.datetime(2017, 11, 15, 9, 25, 37, 615500), max_length=100),
        ),
        migrations.AlterField(
            model_name='members',
            name='register_date',
            field=models.CharField(default=datetime.datetime(2017, 11, 15, 9, 25, 37, 599500), max_length=100),
        ),
        migrations.AlterField(
            model_name='sending_profiles',
            name='created_date',
            field=models.CharField(default=datetime.datetime(2017, 11, 15, 9, 25, 37, 618000), max_length=100),
        ),
        migrations.AlterField(
            model_name='userss',
            name='sent_date',
            field=models.CharField(default=datetime.datetime(2017, 11, 15, 9, 25, 37, 616000), max_length=100),
        ),
        migrations.AddField(
            model_name='phish_data',
            name='group_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='services.groups'),
        ),
        migrations.AddField(
            model_name='phish_data',
            name='member_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='services.members'),
        ),
        migrations.AddField(
            model_name='phish_data',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='services.quick_attack'),
        ),
    ]
